### ISSUE TITLE
Y Axis Scale Cuts Off Graph

### ISSUE THREAD

**Issue by kevinkey** [theiviaxx/MilkChart#10]
In this table the Y Axis scale should go to 5, but is only going to 4 and you can see the points running off the graph.

<table class="Line"><thead><tr><th>Brightness</th><th>Slope</th></tr></thead><tbody><tr><td>4.444302005486</td><td>0</td></tr><tr><td>4.442793720558</td><td>-0.01069115143339</td></tr><tr><td>4.440700537516</td><td>-0.0108549757031</td></tr><tr><td>4.440734256702</td><td>0.000168027768734</td></tr><tr><td>4.404716943466</td><td>-0.1808325415929</td></tr><tr><td>4.304194730155</td><td>-0.5024161864577</td></tr><tr><td>4.153908101255</td><td>-0.7501150289028</td></tr><tr><td>4.005559022866</td><td>-0.7232277750887</td></tr><tr><td>3.895574663047</td><td>-0.5645948947067</td></tr><tr><td>3.772102602267</td><td>-0.6167592839667</td></tr><tr><td>3.629847629386</td><td>-0.7113901429051</td></tr><tr><td>3.495349376935</td><td>-0.6713239059289</td></tr><tr><td>3.387593075655</td><td>-0.5428689351699</td></tr><tr><td>3.245910033243</td><td>-0.6872057626351</td></tr><tr><td>3.121202029448</td><td>-0.6419946098951</td></tr><tr><td>2.994778249438</td><td>-0.6313081262222</td></tr><tr><td>2.854786354186</td><td>-0.6986229879959</td></tr><tr><td>2.748669316098</td><td>-0.5328870157424</td></tr><tr><td>2.614798760589</td><td>-0.6667353177071</td></tr><tr><td>2.469026618461</td><td>-0.7275422504136</td></tr><tr><td>2.326784608544</td><td>-0.6932329558665</td></tr><tr><td>2.19417074836</td><td>-0.6838799997258</td></tr><tr><td>2.066477307197</td><td>-0.6358045073789</td></tr><tr><td>1.952084802214</td><td>-0.5717512315584</td></tr><tr><td>1.809951730675</td><td>-0.7119788451425</td></tr><tr><td>1.674393916293</td><td>-0.6798333521706</td></tr><tr><td>1.567659570543</td><td>-0.5148540102036</td></tr><tr><td>1.427810327765</td><td>-0.7220291450137</td></tr><tr><td>1.311991237363</td><td>-0.5830870096816</td></tr><tr><td>1.164718591195</td><td>-0.7151563662301</td></tr><tr><td>1.062387182985</td><td>-0.5269713581916</td></tr><tr><td>0.922517208862</td><td>-0.6923937127439</td></tr><tr><td>0.7976107890626</td><td>-0.6309961143119</td></tr><tr><td>0.6722997289103</td><td>-0.6349111249885</td></tr><tr><td>0.54423537155</td><td>-0.629900148386</td></tr><tr><td>0.4089239676784</td><td>-0.6751453958393</td></tr><tr><td>0.2699579256067</td><td>-0.6985107244998</td></tr><tr><td>0.1357462955869</td><td>-0.6657002966333</td></tr><tr><td>0.09994425529845</td><td>-0.1796439194943</td></tr><tr><td>0.08842784246172</td><td>-0.05770693052393</td></tr><tr><td>0.07536293482113</td><td>-0.06546871975088</td></tr><tr><td>0.05532203070973</td><td>-0.09974856589792</td></tr><tr><td>0.04668341766317</td><td>-0.04325589681495</td></tr><tr><td>0.04207684841832</td><td>-0.02263617475335</td></tr><tr><td>0.0401924604508</td><td>-0.009576409781799</td></tr><tr><td>0.03737819824213</td><td>-0.01411715181647</td></tr><tr><td>0.03748324700103</td><td>0.000524801650862</td></tr><tr><td>0.0398474867158</td><td>0.01187307239722</td></tr><tr><td>0.03745730932216</td><td>-0.01190115496349</td></tr><tr><td>0.04091223728457</td><td>0.01725418862825</td></tr></tbody><tfoot><tr><td>0.000</td><td>0.141</td><td>0.334</td><td>0.535</td><td>0.734</td><td>0.934</td><td>1.134</td><td>1.339</td><td>1.534</td><td>1.734</td><td>1.934</td><td>2.135</td><td>2.333</td><td>2.539</td><td>2.734</td><td>2.934</td><td>3.134</td><td>3.333</td><td>3.534</td><td>3.734</td><td>3.940</td><td>4.134</td><td>4.334</td><td>4.534</td><td>4.734</td><td>4.934</td><td>5.141</td><td>5.335</td><td>5.533</td><td>5.739</td><td>5.933</td><td>6.135</td><td>6.333</td><td>6.531</td><td>6.734</td><td>6.934</td><td>7.133</td><td>7.335</td><td>7.534</td><td>7.734</td><td>7.933</td><td>8.134</td><td>8.334</td><td>8.537</td><td>8.734</td><td>8.934</td><td>9.134</td><td>9.333</td><td>9.534</td><td>9.734</td></tr></tfoot></table>

**Comment by theiviaxx** [comment]
I was unable to reproduce this in 1.4 or 1.5.  Let me know if it still happens
