### ISSUE TITLE
Gaps in line chart

### ISSUE THREAD

**Issue by kraiz** [theiviaxx/MilkChart#13]
It seems for now it's not possible to have gaps in a line chart.

Is this easy to implement?

**Comment by theiviaxx** [comment]
Yeah, should be easy to accomplish

**Comment by kraiz** [comment]
I think i made it, take a look at 8de7454fbf006900303a1e1d2367b98c5ead1927 (contains MooTools 1.4 changes as well). Shall i send you a pull request?

**Comment by theiviaxx** [comment]
holy crap, im sorry about the delay here.  Can you submit a pull request?  i'll take care of any conflicts
