### ISSUE TITLE
Title missing in select browsers

### ISSUE THREAD

**Issue by jswing83** [theiviaxx/MilkChart#14]
I was viewing the demo page (http://www.brettdixon.com/demos/charts.html) and noticed that the titles were not displaying in Chrome, Internet Explorer and Opera.  They were visible in Firefox and Safari.  I don't know if this is an issue the browsers or an issue with your script.

**Comment by theiviaxx** [comment]
I believe this has been fixed.  All I have is cloud9 right now so i couldn't really test it.

**Comment by theiviaxx** [comment]
confirmed as fixed
