### ISSUE TITLE
TypeError: Cannot call method 'getChildren' of undefined

### ISSUE THREAD

**Issue by tmaciejewski** [theiviaxx/MilkChart#15]
When adding tfoot header I get "TypeError: Cannot call method 'getChildren' of undefined". Without tfoot there's no error, but the chart has default labels: 1, 2, 3, 4.

Here's my table:

``` html
<table id="chart">
   <thead><tr><th>Power usage</th></tr></thead>
   <tbody>
      <tr><td>11</td></tr>
      <tr><td>22</td></tr>
      <tr><td>33</td></tr>
      <tr><td>44</td></tr>
   </tbody>
   <tfoot>
      <tr><td>10</td><td>20</td><td>30</td><td>40</td></tr>
   </tfoot>
</table>
```

**Comment by theiviaxx** [comment]
Im trying to repro this, but cant get it to fail.  I used your table html provided.  What version of mootools do you have?
