### ISSUE TITLE
Line chart fails to render when value > 99,999

### ISSUE THREAD

**Issue by leegee** [theiviaxx/MilkChart#16]
First time user, may be operator error, but my values are > 99,999 and I'm getting no output. When I force lower values, it works.

Is there a feature to render values on a scale that the data covers, rather than from 0 to the highest data value?

Otherwise -- lovely code, looks great, and the idea of using a table to pass data is superb.

**Comment by theiviaxx** [comment]
Yeah, there is a limit of 10000.  I checked how excel does it and it looks like its a normal interval after certain values.  I'll put in a fix

**Comment by theiviaxx** [comment]
as to your second question, yes, the config takes an arg: useZero.  Set that to false, and it will use the min/max of the values provided

**Comment by theiviaxx** [comment]
Fixed in 1.5.5
