### ISSUE TITLE
No Line graph for big values

### ISSUE THREAD

**Issue by zipz** [theiviaxx/MilkChart#3]
I get no trend if I have values higher than 10,000 (or close to 10,000 not sure for the exact number).
Using google chrome 6.0. See code below for example.
http://www.glowfoto.com/static_image/15-095153L/2499/jpg/09/2010/img5/glowfoto

**Comment by theiviaxx** [comment]
This has been fixed.  It had to do with the logic in finding the horizontal lines.  this is still prone to failure.  Not sure what algorithm excel is using to find these numbers.

**Comment by zipz** [comment]
Increasing the dist solves the problem. See below.
dist = [1, 2, 5, 10, 20, 50, 100, 150, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000];
EDIT
I saw your solution and it was something similar.
