### ISSUE TITLE
Data from JSON

### ISSUE THREAD

**Issue by theiviaxx** [theiviaxx/MilkChart#8]
This works with the .load() method, but users may already have the JSON data and want to give it to the constructor.

**Comment by lpilon** [comment]
Fixed: https://github.com/elguapo/MilkChart

**Comment by leegee** [comment]
I'm not clear if the 'fix' allows users to pass JSON to the chart, could you please clarify?

I find my data needs to massaged before it can be laid out as a chart, and I want to do that in the client not on the server. This means making a request, constructing a table from a mustache.js template, then filling the template, then passing the templated data to MilkChart — such a hassle doing it six times that I was going to write a module of ode to do the job.

**Comment by theiviaxx** [comment]
When you call the .load cuntion of the object, you can pass it an onLoad function that takes a JSON object and returns a JSON object.  This is where you can do the massaging of the data.  The return data needs to be formatted in the way MilkChart expects:

```
{
    "colNames": [],
    "rowNames": [],
    "rows": [],
    "title": ""
}
```

**Comment by leegee** [comment]
That's very handy! Thanks! Sorry if I missed that in the docs.

**Comment by theiviaxx** [comment]
No worries, when i implemented it i ran into the same thing and didnt want everyone to bend server side stuff to the will of a client side plugin
