### ISSUE TITLE
Y Axis Labels Limit Precision

### ISSUE THREAD

**Issue by kevinkey** [theiviaxx/MilkChart#9]
Sometimes there will be a Y Axis Label displaying the full double precision, ie. "3.9999999999996" instead of "4". I have an example image, but I don't see a way of posting it.

**Comment by theiviaxx** [comment]
what does the table/data look like?

**Comment by kevinkey** [comment]
It's kind of a big table.

<table class="Line"><thead><tr><th>Brightness</th><th>Slope</th><th>Exp</th></tr></thead><tbody><tr><td>4.259009899736</td><td>0</td><td>0</td></tr><tr><td>4.257244829971</td><td>-0.01276693683852</td><td>0</td></tr><tr><td>4.251312846726</td><td>-0.02965508900258</td><td>0</td></tr><tr><td>4.232647979242</td><td>-0.09089051678004</td><td>0</td></tr><tr><td>4.220357306407</td><td>-0.06320365972129</td><td>0</td></tr><tr><td>4.111121255095</td><td>-0.5464639438901</td><td>0</td></tr><tr><td>3.98854792743</td><td>-0.6135878378672</td><td>0</td></tr><tr><td>3.856284217652</td><td>-0.6609407820331</td><td>0</td></tr><tr><td>3.741963029273</td><td>-0.5675962236901</td><td>0</td></tr><tr><td>3.600143808263</td><td>-0.7213407448312</td><td>0</td></tr><tr><td>3.479172151715</td><td>-0.5992844804691</td><td>0</td></tr><tr><td>3.362843364804</td><td>-0.5813415017481</td><td>0</td></tr><tr><td>3.235261451962</td><td>-0.6362117561682</td><td>0</td></tr><tr><td>3.119413818261</td><td>-0.578376422143</td><td>0</td></tr><tr><td>2.964791653423</td><td>-0.7575239101732</td><td>0</td></tr><tr><td>2.876324054871</td><td>-0.4528915810373</td><td>0</td></tr><tr><td>2.763467050554</td><td>-0.566950971071</td><td>0</td></tr><tr><td>2.631399176038</td><td>-0.6556904953227</td><td>0</td></tr><tr><td>2.502947051811</td><td>-0.6433635465167</td><td>0</td></tr><tr><td>2.353013148174</td><td>-0.7513597585207</td><td>0</td></tr><tr><td>2.233339675697</td><td>-0.5966907988498</td><td>0</td></tr><tr><td>2.096871428333</td><td>-0.6836887495379</td><td>0</td></tr><tr><td>1.992188760355</td><td>-0.521709327538</td><td>0</td></tr><tr><td>1.850047905284</td><td>-0.7138923674542</td><td>0</td></tr><tr><td>1.761943426465</td><td>-0.4391331713342</td><td>0</td></tr><tr><td>1.619071124099</td><td>-0.7203727480157</td><td>0</td></tr><tr><td>1.494171176442</td><td>-0.6033146938346</td><td>0</td></tr><tr><td>1.390299061445</td><td>-0.520010868337</td><td>0</td></tr><tr><td>1.237458834004</td><td>-0.784033465011</td><td>0</td></tr><tr><td>1.133357186146</td><td>-0.5218121833938</td><td>0</td></tr><tr><td>0.9998004642655</td><td>-0.6802091027716</td><td>0</td></tr><tr><td>0.893606911669</td><td>-0.5229406355571</td><td>0</td></tr><tr><td>0.7742278474511</td><td>-0.5925981779418</td><td>0</td></tr><tr><td>0.6464448993953</td><td>-0.6411775045495</td><td>0</td></tr><tr><td>0.5384460693048</td><td>-0.5426042997239</td><td>0</td></tr><tr><td>0.398144214591</td><td>-0.7114418735696</td><td>0</td></tr><tr><td>0.2736398226237</td><td>-0.6140730205734</td><td>0</td></tr><tr><td>0.1569699524439</td><td>-0.5821319989154</td><td>0</td></tr><tr><td>0.123925109324</td><td>-0.1646821029346</td><td>0</td></tr><tr><td>0.1111403294322</td><td>-0.06428794924596</td><td>0</td></tr><tr><td>0.1112752073975</td><td>0.0006689321805941</td><td>0</td></tr><tr><td>0.1028661513515</td><td>-0.04222984438007</td><td>0</td></tr><tr><td>0.1053341419646</td><td>0.01234674742375</td><td>0</td></tr><tr><td>0.103737663355</td><td>-0.00796410346463</td><td>0</td></tr><tr><td>0.1164212824682</td><td>0.06364410043491</td><td>0</td></tr><tr><td>0.1031047780233</td><td>-0.0675555245116</td><td>0</td></tr><tr><td>0.1165665337684</td><td>0.06647338517382</td><td>0</td></tr><tr><td>0.1024731923302</td><td>-0.06833947466036</td><td>0</td></tr><tr><td>0.1184042318326</td><td>0.08202195150183</td><td>0</td></tr><tr><td>0.1241650394637</td><td>0.02797065870273</td><td>0</td></tr></tbody><tfoot><tr><td>0.000</td><td>0.139</td><td>0.339</td><td>0.544</td><td>0.738</td><td>0.938</td><td>1.138</td><td>1.338</td><td>1.540</td><td>1.736</td><td>1.938</td><td>2.138</td><td>2.339</td><td>2.539</td><td>2.743</td><td>2.938</td><td>3.138</td><td>3.339</td><td>3.539</td><td>3.738</td><td>3.939</td><td>4.138</td><td>4.339</td><td>4.538</td><td>4.739</td><td>4.937</td><td>5.144</td><td>5.344</td><td>5.539</td><td>5.738</td><td>5.935</td><td>6.138</td><td>6.339</td><td>6.538</td><td>6.737</td><td>6.935</td><td>7.137</td><td>7.338</td><td>7.538</td><td>7.737</td><td>7.939</td><td>8.138</td><td>8.338</td><td>8.538</td><td>8.738</td><td>8.935</td><td>9.137</td><td>9.344</td><td>9.538</td><td>9.744</td></tr></tfoot></table>

**Comment by theiviaxx** [comment]
Fixed in 1.5
